version: "3.8"
services:
  server:
    build:
      context: ./server
    container_name: server
    ports:
      - "9443:9443" # 포트 매핑
    volumes:
      - ./server/data:/data
      - ./shared:/shared
      # 헬스체크를 10초마다 한 번씩 실행하여 서버가 작동하는지 확인
      # 서버가 5번 연속으로 헬스체크에 실패하면, Docker는 서버가 비정상 상태로 간주
    healthcheck:
      test: ["CMD", "netstat", "-tuln", "|", "grep", "9443"]
      # netstat -tuln | grep 9443 을 통해 서버의 9443포트가 LISTEN 상태인지 확인
      interval: 5s
      retries: 2
    restart: unless-stopped

  client:
    build:
      context: ./client
    container_name: client
    depends_on:
      server:
        condition: service_healthy
    volumes:
      - ./shared:/shared
    restart: on-failure
